apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: MTIzNDU2
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWNsYXZlX2ZlcnJldGVyaWFfdGVzdGluZ18yMDI2
